config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'

  resources :orders
  resources :books
  resources :home
  
<<<<<<< HEAD
  get 'signup'  => 'admins#new' 
  resources :admins
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
=======
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
  resources :sessions
  

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email,password)
    @user = find_by_email(email)
    if @user
      if @user.password == password
      @user
    else
      nil
    end
  end
end

end

  
#   def encrypt_password
#     if password.present?
#       self.password_salt = BCrypt::Engine.generate_salt
#       self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
#     end
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
<<<<<<< HEAD


  helper_method :current_admin

  def current_admin 
  @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id] 
  end
  
  def require_admin 
  redirect_to '/login' unless current_admin 
  end

=======
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
<<<<<<< HEAD
  before_action :require_admin, only: [:index, :show]
=======
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :coursecode, :instructor, :price, :semester, :dept)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
    @home = Order.all
end
def new
end

def create
end

def destroy
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
<<<<<<< HEAD
  before_action :require_admin, only: [:index, :show]
=======
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @k = params[:bid]
    flash[:var] = @k
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @r = flash[:var]
    
    
    @order = Order.new( { "customer" => order_params["customer"], "bid" => @r, "email" => order_params["email"], "mobile"=> order_params["mobile"],"status" => 0})

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer, :bid, :email, :mobile, :status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
<<<<<<< HEAD
    def new
    end
    
  def create
  @admin = Admin.find_by_email(params[:session][:email])
  if @admin && @admin.authenticate(params[:session][:password])
    session[:admin_id] = @admin.id
    redirect_to '/'
  else
    redirect_to 'login'
  end 
  end

  def destroy 
  session[:admin_id] = nil 
  redirect_to '/' 
  end

    
=======
def new
end

def create
  user = User.authenticate(params[:email],params[:password])
  if user
    session[:user_id] = user.id
    redirect_to books_path, :notice => "Logged in!"
  else
    flash[:notice] = "Inavlid"
    redirect_to log_in_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  #   @user = User.authenticate(params[:email])
  # if @user
    @user= User.create!(params[:email], params[:password])
    redirect_to root_url, :notice => "Signed up!"
  # else
  #   render "new"
  # end
end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :coursecode, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :coursecode, :class => 'form-control' %>
    </div>
    <%=f.error_span(:coursecode) %>
  </div>
  <div class="form-group">
    <%= f.label :instructor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :instructor, :class => 'form-control' %>
    </div>
    <%=f.error_span(:instructor) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :semester, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :semester, :class => 'form-control' %>
    </div>
    <%=f.error_span(:semester) %>
  </div>
  <div class="form-group">
    <%= f.label :dept, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dept, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dept) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:coursecode) %></th>
      <th><%= model_class.human_attribute_name(:instructor) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:semester) %></th>
      <th><%= model_class.human_attribute_name(:dept) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td><%= book.coursecode %></td>
        <td><%= book.instructor %></td>
        <td><%= book.price %></td>
        <td><%= book.semester %></td>
        <td><%= book.dept %></td>
        <td><%=l book.created_at %></td>
        <td>
          <%= link_to t("BUY", :default => "BUY"),
                      new_order_path(:bid => book), :class => 'btn btn-default btn-xs' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @book.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coursecode) %>:</strong></dt>
  <dd><%= @book.coursecode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:instructor) %>:</strong></dt>
  <dd><%= @book.instructor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @book.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:semester) %>:</strong></dt>
  <dd><%= @book.semester %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dept) %>:</strong></dt>
  <dd><%= @book.dept %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="#">1 Point</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" />
						</div> 
						<button type="submit" class="btn btn-default">
							Search
						</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="/orders/new">Sign In   </a>
						</li>

					
					</ul>
				</div>
<<<<<<< HEAD
				<% if current_admin %> 
  <ul> 
    <li><%= current_admin.email %></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  </ul> 
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
  </ul> 
<% end %>
=======
>>>>>>> c33b1a0ef979b662fbdf8f496c663676bd106d28
				
			</nav>
		 <%= yield %>
</div>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :customer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:customer) %>
  </div>
  
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :mobile, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mobile, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mobile) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer) %></th>
      <th><%= model_class.human_attribute_name(:bid) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order) %></td>
        <td><%= order.customer %></td>
        <td><%= order.bid %></td>
        <td><%= order.email %></td>
        <td><%= order.mobile %></td>
        <td><%= order.status %></td>
        <td><%=l order.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_path(order), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_path(order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
 
  <h1><%= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer) %>:</strong></dt>
  <dd><%= @order.customer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bid) %>:</strong></dt>
  <dd><%= @order.bid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @order.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @order.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @order.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<p> Thankyou for plcing your orer. </p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>